name: Deploy to Vercel

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to Vercel
        env:
          # Quote the expression to avoid some YAML/VSCode linters complaining about context access
          VERCEL_TOKEN: "${{ secrets.VERCEL_TOKEN }}"
          # Optional: set VERCEL_ORG_ID and VERCEL_PROJECT_ID for explicit targeting
          # VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          # VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          npm i -g vercel@33.0.0
          # Use the token to deploy non-interactively
          vercel --token $VERCEL_TOKEN --prod --confirm
